### ISSUE TITLE
Feature request: allow passing an optional validator function to make?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [kourge/ts-brand#8]
👋 again, great library! As I understand it, right now `make` only supports a pass-through `identity`-style usage:

```ts
import { Brand, make } from "ts-brand";

type Integer = Brand<number, 'integer'>;
const Integer = make<Integer>();

const myInteger = Integer(42);
```

In real world type brands, I've found that folks sometimes have functions that take in a value, throw if it doesn't match a type brand's known restrictions, and otherwise behave the same as `make`. For example, with integers:

```ts
import { Brand } from "ts-brand";

type Integer = Brand<number, 'integer'>;

function Integer(value: number) {
  if (value !== Math.floor(value)) {
    throw new Error(`${value} is not an integer.`);
  }

  return value as Integer;
}

const myInteger = Integer(42);
```

Would you be open to expanding `make` to take in an optional `validator: (value: BaseOf<B>) => asserts value is B`? That way we could use it to recreate the asserted `Integer` like:

```ts
import { Brand, make } from "ts-brand";

type Integer = Brand<number, 'integer'>;
const Integer = make<Integer>(
  (value) => {
    if (value !== Math.floor(value)) {
      throw new Error(`${value} is not an integer.`);
    }
  }
);

const myInteger = Integer(42);
```

I'd be happy to send in a PR!

**Comment by kourge** [comment]
I initially created `make` because it acts as a simple training-wheels-type convenience for when you don't need to perform any further validation. Based on just that, I would have taken the position that this feature would over-complicate things.

However, two things are different now:
1. Your proposed feature does not break any existing usage of `make()`.
2. We've had assertion functions since TypeScript 3.7.

Based on these factors, I am open to such a change. I'm assuming that you've got something like this in mind?
```ts
type AssertionFunction<T> = (value: unknown) => asserts value is T;

declare function make<B extends AnyBrand>(validator?: AssertionFunction<B>): Brander<B>;
```

**Comment by JoshuaKGoldberg** [comment]
Yup, that! It's a little tricky with the generic types but I'm going to try for something as close to that & simple as possible. Thanks!
